name: telegram members yotas
on: [push]
  

jobs:
  build:
    defaults:
      run:
        working-directory: ./.github/workflows/yotas 

    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        run: echo "hello world"
      - name: number of yotas of each members
        run: https://miniyotas.osscameroon.com/v1/api/records 
        
      
