name: telegram members yotas
on: [push]
  

jobs:
  build:
    defaults:
      run:
        working-directory: ./.github/workflows/send_message

    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: number of yotas of each members
        run: python message_file.py > messagefile 

      - name: send custom message to osscameroon channel 
        uses: appleboy/telegram-action@master
        with: 
          to: -605306244
          token: 2010406336:AAF2LZgVui0xTd5TZ0FG7w3wQj4n0YKbdHY
          format: MarkdownV2
          message_file: ./.github/workflows/send_message/messagefile
        
      
 